[[OpenCV]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a93f2a6f434823728ac0033f8208d469ab71b663"
libc = "glibc"
os = "linux"

    [[OpenCV.download]]
    sha256 = "e8dedea2726239497cc27bf0ddaaa03d0ae156f8878ed451ed3c65f1913bb90e"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.2.0+0/OpenCV.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenCV]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a9f5246b926b4e8ca71b20c132ae61cef4be251"
libc = "glibc"
os = "linux"

    [[OpenCV.download]]
    sha256 = "1e4090f5cb86283ac4d94dc76ce68c344f4b7a52e44b61dfef9898efd9412c6f"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.2.0+0/OpenCV.v0.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenCV]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63aee7815b0035d8bf74a42764b5e16109c1b381"
libc = "glibc"
os = "linux"

    [[OpenCV.download]]
    sha256 = "01fce0b51cacac8912ba303d36c3179d3bad26c4e1b3836abedd3c559b8bc95e"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.2.0+0/OpenCV.v0.2.0.i686-linux-gnu-cxx11.tar.gz"
[[OpenCV]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db86ad5b903bd699bffda9a83b180775fd4fb4cc"
os = "windows"

    [[OpenCV.download]]
    sha256 = "2c17a7f927bfcf1726c609cbc8e77f88a7aea2aa5b3d202cb52dd6cb94440c70"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.2.0+0/OpenCV.v0.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[OpenCV]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ed159d402b65d73e69c8fb23543acc66a959e3b"
os = "macos"

    [[OpenCV.download]]
    sha256 = "d98cdc287b3b62a6ebcd921f43737e36f037989e53fff9970d12f76be2783143"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.2.0+0/OpenCV.v0.2.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[OpenCV]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59333b0a1bf9d397ca284168c89e946b922ffd8b"
os = "windows"

    [[OpenCV.download]]
    sha256 = "8854d33049b78cf71d9f184af03eb7cc76f5ad59c8e75056eddc8b3600b9130e"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.2.0+0/OpenCV.v0.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[OpenCV]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b709cc5456d3ed3ed7df36d2abaf4ff3ff03106"
libc = "glibc"
os = "linux"

    [[OpenCV.download]]
    sha256 = "ba12d38921a8d661e330f9e03bcd33ca18382e6f9b09ffe7fa871960fbcc950e"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.2.3+0/OpenCV.v0.2.3.x86_64-linux-gnu-cxx11.tar.gz"
