[[OpenCV]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d22811cab50183836cdafd440a480c453549d005"
libc = "glibc"
os = "linux"

    [[OpenCV.download]]
    sha256 = "1f6a72f9ef3a0f85ccb25070a71fc339c6f1b51809d2db34b910b7fc79099040"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.1.0+0/OpenCV.v0.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenCV]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74b5f9570570fef0ea8a042a033f0c99a7044ece"
os = "macos"

    [[OpenCV.download]]
    sha256 = "dcd48c3ddc48827af22a6c5f81ec630da8d602a5e6af040a4f4e9dbbfdb57ce0"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.1.0+0/OpenCV.v0.1.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[OpenCV]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ba999c9c3083992cf13243dc9221cda7eb6a0fb"
libc = "glibc"
os = "linux"

    [[OpenCV.download]]
    sha256 = "604cc5a227f6058b24a9eb4fa6b0d21592a23f9a46f0949b86b0c6ee8afefe7c"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.1.0+0/OpenCV.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenCV]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "547441315c0b4130775d542e5bd374299e4c238b"
os = "windows"

    [[OpenCV.download]]
    sha256 = "de4ce6da8aa183ab39728a9d695b7ccc08e182c577e9f5213bb04bf1e339a478"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.1.0+0/OpenCV.v0.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
