[[OpenCV]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fedcd7f63d5213284dd9e3d1a7cdb09be2e9a91"
libc = "glibc"
os = "linux"

    [[OpenCV.download]]
    sha256 = "deef0f663777a3abf80766df6fea6002c07b51de393b50e7a11109a5086dc64e"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.4.0+0/OpenCV.v0.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenCV]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba3b2b2fc391cbcb9b8d0869e81ff7a4a0e9664b"
libc = "glibc"
os = "linux"

    [[OpenCV.download]]
    sha256 = "bcce1176757cf3509dc248391fe307612c4d29e9c875ee04dae6de80e709adc3"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.4.0+0/OpenCV.v0.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenCV]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58648c93673668be7d342d4f19b6b29b2700e894"
libc = "glibc"
os = "linux"

    [[OpenCV.download]]
    sha256 = "7e4555676eb24558386365146ed2155cadabad596dfef3402345612056298bdf"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.4.0+0/OpenCV.v0.4.0.i686-linux-gnu-cxx11.tar.gz"
[[OpenCV]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "818b196534e19fed3b1cf30a52583e1ff59bf6c8"
os = "windows"

    [[OpenCV.download]]
    sha256 = "2d6defad60a1fc70a42f349d0e3698a51a3e756354d4eb23722effd62597a52e"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.4.0+0/OpenCV.v0.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[OpenCV]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e434aab2547d23a796df10942f19d5775ed37b59"
os = "macos"

    [[OpenCV.download]]
    sha256 = "ab6ca641ae170b5933c2b0bcb7e0377ec7ea6a32cc7e4fa7fd982a32e0965da2"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.4.0+0/OpenCV.v0.4.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[OpenCV]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6809e60575352a327daeae343b47d4245911d099"
libc = "glibc"
os = "linux"

    [[OpenCV.download]]
    sha256 = "47c7bcfcf49886460b3d25181930454492ca410da3ea0de647dd5acae23a75fc"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.4.0+0/OpenCV.v0.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenCV]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00d73b517f9683a3b038b1e55dfa27d883e282dd"
os = "windows"

    [[OpenCV.download]]
    sha256 = "39e87704659f01d3cfb79763530197e905812cf4df38a9af078138a738026b5c"
    url = "https://github.com/terasakisatoshi/OpenCV_jll.jl/releases/download/OpenCV-v0.4.0+0/OpenCV.v0.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
